### ISSUE TITLE
IOS Support

### ISSUE THREAD

**Issue by richard-ramos** [vacp2p/zerokit-mobile#2]
- [ ] https://github.com/vacp2p/zerokit-mobile/issues/4
- [ ] https://github.com/vacp2p/zerokit-mobile/issues/5
- [ ] https://github.com/vacp2p/zerokit-mobile/issues/3
- [ ] https://github.com/vacp2p/zerokit-mobile/issues/6
